name: build jobs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out the repository code

    - name: dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: build directory
      run: mkdir build

    - name: CMake
      run: cmake ..
      working-directory: ./build

    - name: Build 
      run: cmake --build . --config Release
      working-directory: ./build

    - name: Run tests (optional)
      run: ctest -C Release  -VV
      working-directory: ./build
